stages:
  - test
  - build
  - deploy

license check:
  image: golang:1.16
  stage: test
  script:
    - ./licensebot-check.sh

build:
  image: golang:1.16
  stage: build
  artifacts:
    paths:
      - stl-to-3mf
    expire_in: 1 day
  variables:
    GOOS: linux
    GOARCH: amd64
  before_script:
    - env GOOS=linux GOARCH=amd64
  script:
    - go build

deploy dev:
  image: napp/docker-aws-cli
  stage: deploy
  dependencies:
    - build
  only:
    - master
  environment:
    name: development
  script:
    - aws s3 cp ./stl-to-3mf s3://$AWS_BUCKET/go-utils/stl-to-3mf-development

deploy prod:
  image: napp/docker-aws-cli
  stage: deploy
  dependencies:
    - build
  only:
    - production
  environment:
    name: production
  script:
    - aws s3 cp ./stl-to-3mf s3://$AWS_BUCKET/go-utils/stl-to-3mf-production
