name: Licensebot Check
description: Check dependency licenses
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
    - run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash
    - run: echo "PATH=${PATH}:$(go env GOPATH)/bin" >> $GITHUB_ENV
      shell: bash
    - run: GOOS=linux GOARCH=amd64 ./licensebot-check.sh
      shell: bash
