name: PR Workflow

on:
  pull_request:

jobs:
  licensebot:
    name: Licensebot Check
    runs-on: ubuntu-latest
    # if source branch is development or production, there will already be jobs from
    # the "push" workflow associated with this PR, so nothing needs to be re-run
    if: github.head_ref != 'development' && github.head_ref != 'production'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/license-check

  build:
    name: Compile
    runs-on: ubuntu-latest
    # if source branch is development or production, there will already be jobs from
    # the "push" workflow associated with this PR, so nothing needs to be re-run
    if: github.head_ref != 'development' && github.head_ref != 'production'
    needs: ['licensebot']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

  checkversion:
    name: Check Version was updated
    runs-on: ubuntu-latest
    if: github.head_ref != 'development' && github.head_ref != 'production'
    steps:
      - name: Check if version file was updated
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            version:
              - version.txt
      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.version_any_changed == 'false'  
        run: |
          echo "Did not update version.txt"
          exit 1